CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS raaw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts;
CREATE SCHEMA IF NOT EXISTS snapshots;
CREATE SCHEMA IF NOT EXISTS ai;

CREATE ROLE dbt_role;

GRANT USAGE ON SCHEMA bronze TO ROLE dbt_role;
GRANT USAGE ON SCHEMA raaw TO ROLE dbt_role;
GRANT USAGE ON SCHEMA staging TO ROLE dbt_role;
GRANT USAGE ON SCHEMA marts TO ROLE dbt_role;
GRANT USAGE ON SCHEMA snapshots TO ROLE dbt_role;
GRANT USAGE ON SCHEMA ai TO ROLE dbt_role;

GRANT CREATE ON SCHEMA bronze TO ROLE dbt_role;
GRANT CREATE ON SCHEMA raaw TO ROLE dbt_role;
GRANT CREATE ON SCHEMA staging TO ROLE dbt_role;
GRANT CREATE ON SCHEMA marts TO ROLE dbt_role;
GRANT CREATE ON SCHEMA snapshots TO ROLE dbt_role;
GRANT CREATE ON SCHEMA ai TO ROLE dbt_role;

GRANT ROLE dbt_role TO "IAM:RootIdentity";